apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - secrets.yaml

helmCharts:
  - name: authentik
    version: 2025.12.4
    repo: https://charts.goauthentik.io
    releaseName: authentik
    valuesFile: values.yaml