apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - secrets.yaml

helmCharts:
  - name: kube-prometheus-stack
    version: 82.4.3
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    includeCRDs: true
    valuesFile: values.yaml