renovate:
  mendRnvAcceptTos: true
  
  # Platform configuration
  platform: github
  endpoint: https://api.github.com/

  existingSecret: mend-renovate-ce-secrets

ingress:
  enabled: true
  ingressClassName: traefik
  tls:
    - hosts:
        - renovate.geeklabs.dev
  hosts:
    renovate.geeklabs.dev:
      paths:
        - path: /
          pathType: ImplementationSpecific