apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - secrets.yaml

helmCharts:
  - name: headlamp
    version: 0.40.0
    repo: https://kubernetes-sigs.github.io/headlamp/
    releaseName: headlamp
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.yaml